#!/usr/bin/env python3
"""
╔══════════════════════════════════════════════════════════╗
║     GDrive Advanced Downloader — Universal Script        ║
║  Verify · Download · Fix · Resume · Batch · Progress     ║
╚══════════════════════════════════════════════════════════╝
"""

import os
import re
import sys
import json
import subprocess
from pathlib import Path
from datetime import datetime

# ─── Try to import optional libraries ──────────────────────────────────────────
try:
    import gdown
    GDOWN_AVAILABLE = True
except ImportError:
    GDOWN_AVAILABLE = False

try:
    from tqdm import tqdm
    TQDM_AVAILABLE = True
except ImportError:
    TQDM_AVAILABLE = False

# ─── ANSI Color Codes ──────────────────────────────────────────────────────────
class C:
    RESET  = "\033[0m"
    BOLD   = "\033[1m"
    RED    = "\033[91m"
    GREEN  = "\033[92m"
    YELLOW = "\033[93m"
    BLUE   = "\033[94m"
    CYAN   = "\033[96m"
    WHITE  = "\033[97m"
    MAGENTA= "\033[95m"
    DIM    = "\033[2m"

def clr(text, color): return f"{color}{text}{C.RESET}"
def bold(text):        return f"{C.BOLD}{text}{C.RESET}"
def ok(text):          return clr(f"✅ {text}", C.GREEN)
def warn(text):        return clr(f"⚠️  {text}", C.YELLOW)
def err(text):         return clr(f"❌ {text}", C.RED)
def info(text):        return clr(f"ℹ️  {text}", C.CYAN)
def dl(text):          return clr(f"⬇️  {text}", C.BLUE)

# ─── Configuration ─────────────────────────────────────────────────────────────
# 🔗 Google Drive folder URL — update this if you want to scan a different folder
DRIVE_URL  = "https://drive.google.com/drive/folders/1slz_UKL-S_qiJ-iFohxN9E4T8vZkfRHl?usp=sharing"

BASE        = Path("/home/bhargavxharma/DATABASE/Atmanova/EBOOK")
MANIFEST    = BASE / "gdown_full_list.txt"       # auto-generated by option 8
COLLECTION  = BASE / "COLLECTION"                # where files are saved
STATE_FILE  = BASE / ".gdrive_state.json"        # tracks download state for resume

ALL_VIDEO_EXT = {'.mp4', '.mkv', '.mov', '.avi', '.flv', '.wmv', '.webm', '.m4v', '.mpg', '.mpeg'}
ALL_DOC_EXT   = {'.pdf', '.epub', '.docx', '.pptx', '.xlsx', '.ppt', '.doc', '.zip'}
ALL_SUB_EXT   = {'.srt', '.vtt'}
ALL_MEDIA_EXT = {'.jpg', '.jpeg', '.png', '.gif', '.bmp', '.webp', '.m4b', '.mp3', '.flac'}
ALL_WEB_EXT   = {'.html', '.url', '.txt', '.json'}

EXTENSION_GROUPS = {
    "1": ("Videos",        ALL_VIDEO_EXT,  C.RED),
    "2": ("Documents",     ALL_DOC_EXT,    C.BLUE),
    "3": ("Subtitles",     ALL_SUB_EXT,    C.DIM),
    "4": ("Images/Audio",  ALL_MEDIA_EXT,  C.MAGENTA),
    "5": ("Web/Text",      ALL_WEB_EXT,    C.WHITE),
}

# ─── State Management ──────────────────────────────────────────────────────────
def load_state() -> dict:
    """Load the persistent download state from disk."""
    if STATE_FILE.exists():
        try:
            with open(STATE_FILE, "r") as f:
                return json.load(f)
        except Exception:
            pass
    return {"downloaded": [], "failed": [], "skipped": []}

def save_state(state: dict):
    """Persist download state to disk."""
    with open(STATE_FILE, "w") as f:
        json.dump(state, f, indent=2)

# ─── Filename Utilities ────────────────────────────────────────────────────────
def clean_name(name: str) -> str:
    """Sanitise a filename the same way the original scripts do."""
    name = re.sub(r'Retrieving folder contents completed', '', name)
    name = re.sub(r'Building directory structure.*', '', name)
    return re.sub(r'[^\w\s\-\.\[\]\~]', '_', name).strip()

JUNK_PATTERNS = [
    "Retrieving folder", "Building directory",
    "folder contents completed", "Downloading...",
    "From: https://", "To:", "%|"
]
def is_junk_line(s: str) -> bool:
    return any(p in s for p in JUNK_PATTERNS)

# ─── Manifest Parser ───────────────────────────────────────────────────────────
def parse_manifest(skip_ext: set = None) -> list[dict]:
    """
    Parse gdown_full_list.txt and return a list of file records:
      { id, name, ext, rel_dir, abs_path }
    skip_ext: set of extensions to exclude (e.g. VIDEO_EXTENSIONS).
    """
    if not MANIFEST.exists():
        print(err(f"Manifest not found: {MANIFEST}"))
        return []

    with open(MANIFEST, "r", errors="ignore") as f:
        lines = f.readlines()

    records = []
    current_main = ""
    current_sub  = ""

    for raw in lines:
        line = raw.strip()

        # ── Folder lines ──
        fm = re.search(r'Retrieving folder [a-zA-Z0-9_-]+ (.*)', line)
        if fm:
            fname = fm.group(1).strip()
            if is_junk_line(fname):
                continue
            if fname.startswith('['):
                current_main = clean_name(fname)
                current_sub  = ""
            elif fname.startswith('~') or fname == "":
                current_sub = clean_name(fname)
            else:
                current_sub = clean_name(fname)
            continue

        # ── File lines ──
        pm = re.search(r'Processing file ([a-zA-Z0-9_-]+) (.*)', line)
        if not pm:
            continue

        fid   = pm.group(1)
        fname = pm.group(2).strip()

        if is_junk_line(fname) or not fname:
            continue

        ext = Path(fname).suffix.lower()
        if skip_ext and ext in skip_ext:
            continue

        # Build relative directory from current context
        parts = [str(COLLECTION)]
        if current_main:
            parts.append(current_main)
        if current_sub:
            parts.append(current_sub)

        target_dir  = Path(os.path.join(*parts))
        target_path = target_dir / clean_name(fname)

        records.append({
            "id":       fid,
            "name":     fname,
            "ext":      ext,
            "rel_dir":  str(target_dir.relative_to(COLLECTION)),
            "abs_dir":  str(target_dir),
            "abs_path": str(target_path),
        })

    return records

# ─── Simple progress bar (fallback if tqdm not available) ─────────────────────
def simple_bar(current: int, total: int, width: int = 40, label: str = "") -> str:
    pct   = current / max(total, 1)
    filled = int(width * pct)
    bar   = "█" * filled + "░" * (width - filled)
    return f"\r{clr(bar, C.BLUE)} {pct*100:5.1f}%  {label}"

def install_deps():
    """Install tqdm and gdown if missing."""
    missing = []
    if not GDOWN_AVAILABLE:
        missing.append("gdown")
    if not TQDM_AVAILABLE:
        missing.append("tqdm")
    if missing:
        print(info(f"Installing missing packages: {', '.join(missing)}"))
        subprocess.check_call([sys.executable, "-m", "pip", "install", "--quiet"] + missing)
        print(ok("Dependencies installed. Please re-run the script."))
        sys.exit(0)

# ─── Header Banner ────────────────────────────────────────────────────────────
def print_header():
    print(clr("""
╔══════════════════════════════════════════════════════════╗
║        GDrive EBOOK Manager  •  Universal Script         ║
╠══════════════════════════════════════════════════════════╣
║  Manifest : gdown_full_list.txt                          ║
║  Collection: COLLECTION/                                 ║
╚══════════════════════════════════════════════════════════╝""", C.CYAN))
    now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    print(clr(f"  {now}\n", C.DIM))

# ══════════════════════════════════════════════════════════════════════════════
# CHUNK 2 — VERIFY, FIX, DOWNLOAD ENGINE
# ══════════════════════════════════════════════════════════════════════════════

# ─── Verification ─────────────────────────────────────────────────────────────
def scan_parts(search_root: Path = None) -> list[str]:
    """Return all .part files under search_root (default: EBOOK base dir)."""
    root = search_root or BASE
    return [str(p) for p in root.rglob("*.part")]

def scan_zero_bytes(records: list[dict]) -> list[dict]:
    """Return records whose downloaded file exists but is 0 bytes."""
    return [r for r in records if Path(r["abs_path"]).exists()
            and Path(r["abs_path"]).stat().st_size == 0]

def scan_missing(records: list[dict]) -> list[dict]:
    """Return records whose target file does not exist."""
    return [r for r in records if not Path(r["abs_path"]).exists()]

def cmd_verify(skip_ext: set = None):
    """Run a full verification scan and print a report."""
    print(bold(clr("\n── VERIFICATION SCAN ──────────────────────────────────", C.CYAN)))
    skip_ext = skip_ext or ALL_VIDEO_EXT
    records  = parse_manifest(skip_ext=skip_ext)
    if not records:
        return

    total   = len(records)
    missing = scan_missing(records)
    zeros   = scan_zero_bytes(records)
    parts   = scan_parts()

    # ── Part files ──
    if parts:
        print(warn(f"Incomplete (.part) files found: {len(parts)}"))
        for p in parts:
            short = str(Path(p).relative_to(BASE))
            print(f"   {clr('•', C.YELLOW)} {short}")
    else:
        print(ok("No .part files found"))

    # ── Zero-byte files ──
    if zeros:
        print(warn(f"Empty (0-byte) files found: {len(zeros)}"))
        for z in zeros:
            print(f"   {clr('•', C.YELLOW)} {z['name']}")
    else:
        print(ok("No zero-byte files found"))

    # ── Missing files ──
    if missing:
        print(err(f"Missing files: {len(missing)} / {total}"))
        for m in missing[:20]:   # cap display at 20
            print(f"   {clr('•', C.RED)} {m['name']}")
        if len(missing) > 20:
            print(clr(f"   … and {len(missing)-20} more", C.DIM))
    else:
        print(ok(f"All {total} expected files are present"))

    # ── Summary ──
    print(clr("\n── SUMMARY ─────────────────────────────────────────────", C.CYAN))
    print(f"  Total expected  : {bold(str(total))}")
    print(f"  Present & OK    : {clr(str(total - len(missing) - len(zeros)), C.GREEN)}")
    print(f"  Missing         : {clr(str(len(missing)), C.RED if missing else C.GREEN)}")
    print(f"  Zero-byte       : {clr(str(len(zeros)), C.RED if zeros else C.GREEN)}")
    print(f"  .part files     : {clr(str(len(parts)), C.RED if parts else C.GREEN)}")

    if not missing and not zeros and not parts:
        print(f"\n{ok('PERFECT — everything is fully downloaded!')}")
    else:
        print(f"\n{warn('Run option 3 (Fix & Re-download) to repair the issues above.')}")

# ─── Fix Broken / Partial Downloads ───────────────────────────────────────────
def cmd_fix(skip_ext: set = None, dry_run: bool = False):
    """
    1. Delete all .part files.
    2. Delete zero-byte files.
    3. Re-download them via the download engine.
    """
    print(bold(clr("\n── FIX & RE-DOWNLOAD ───────────────────────────────────", C.CYAN)))
    skip_ext = skip_ext or ALL_VIDEO_EXT
    records  = parse_manifest(skip_ext=skip_ext)

    # ── Delete .part files ──
    parts = scan_parts()
    if parts:
        print(info(f"Deleting {len(parts)} .part file(s)…"))
        for p in parts:
            short = str(Path(p).relative_to(BASE))
            if not dry_run:
                os.remove(p)
            print(f"  {clr('deleted', C.RED)} {short}")
    else:
        print(ok("No .part files to clean."))

    # ── Delete zero-byte files ──
    zeros = scan_zero_bytes(records)
    if zeros:
        print(info(f"Deleting {len(zeros)} zero-byte file(s)…"))
        for z in zeros:
            if not dry_run:
                os.remove(z["abs_path"])
            print(f"  {clr('deleted', C.RED)} {z['name']}")
    else:
        print(ok("No zero-byte files to clean."))

    # ── Identify what needs (re)downloading ──
    missing = scan_missing(records)
    # also add back the ones we just deleted
    if zeros:
        deleted_paths = {z["abs_path"] for z in zeros}
        for r in records:
            if r["abs_path"] in deleted_paths and r not in missing:
                missing.append(r)

    if not missing:
        print(ok("Nothing to re-download — collection is complete!"))
        return

    print(info(f"Re-downloading {len(missing)} file(s)…\n"))
    if not dry_run:
        _run_download(missing)
    else:
        for m in missing:
            print(f"  {clr('[DRY-RUN]', C.DIM)} would download: {m['name']}")

# ─── Download Engine ───────────────────────────────────────────────────────────
def _run_download(records: list[dict]):
    """
    Core download loop with:
    - Progress bar (tqdm or fallback)
    - Resume support (skip already-downloaded via state file)
    - Error logging
    """
    if not GDOWN_AVAILABLE:
        print(err("gdown is not installed. Run option 0 → Install dependencies."))
        return

    state  = load_state()
    done   = set(state.get("downloaded", []))
    failed = {}

    to_dl  = [r for r in records if r["abs_path"] not in done
              and not Path(r["abs_path"]).exists()]

    if not to_dl:
        print(ok("All files already present — nothing to download."))
        return

    total = len(to_dl)
    print(f"  {bold(str(total))} file(s) queued for download.\n")

    if TQDM_AVAILABLE:
        bar = tqdm(total=total, unit="file", colour="cyan",
                   bar_format="{l_bar}{bar:30}{r_bar}", dynamic_ncols=True)
    else:
        bar = None

    for i, rec in enumerate(to_dl, 1):
        name    = rec["name"]
        fid     = rec["id"]
        out_dir = Path(rec["abs_dir"])
        out_path= Path(rec["abs_path"])

        out_dir.mkdir(parents=True, exist_ok=True)

        if bar:
            bar.set_description(clr(name[:45], C.CYAN))
        else:
            sys.stdout.write(simple_bar(i, total, label=name[:40]))
            sys.stdout.flush()

        try:
            gdown.download(id=fid, output=str(out_path), quiet=True)
            # Validate result
            if out_path.exists() and out_path.stat().st_size > 0:
                state["downloaded"].append(str(out_path))
                if bar:
                    bar.update(1)
            else:
                # Empty file — clean up and mark failed
                if out_path.exists():
                    out_path.unlink()
                failed[str(out_path)] = "Empty file after download"
        except Exception as e:
            failed[str(out_path)] = str(e)
            if bar:
                bar.update(1)

        # Persist state every 10 files
        if i % 10 == 0:
            state["failed"] = list(failed.keys())
            save_state(state)

    if bar:
        bar.close()
    else:
        print()  # newline after simple bar

    state["failed"] = list(failed.keys())
    save_state(state)

    # ── Summary ──
    n_ok  = total - len(failed)
    print(f"\n{ok(f'{n_ok}/{total} downloaded successfully.')}")
    if failed:
        print(warn(f"{len(failed)} failed:"))
        for path, reason in list(failed.items())[:10]:
            print(f"  {clr('•', C.RED)} {Path(path).name}: {reason}")
        if len(failed) > 10:
            print(clr(f"  … and {len(failed)-10} more (see .gdrive_state.json)", C.DIM))


# ══════════════════════════════════════════════════════════════════════════════
# CHUNK 3 — SELECTIVE DOWNLOAD, BATCH EXTENSION PICKER, MENU
# ══════════════════════════════════════════════════════════════════════════════

# ─── Extension picker ─────────────────────────────────────────────────────────
def pick_extensions() -> set:
    """Interactive menu to select which file types to include/exclude."""
    print(bold(clr("\n── SELECT FILE TYPES ───────────────────────────────────", C.CYAN)))
    print("  Toggle groups ON/OFF. Press ENTER when done.\n")

    active = {"1", "2", "3", "4", "5"}   # all on by default

    while True:
        for key, (label, exts, color) in EXTENSION_GROUPS.items():
            status = clr("ON ", C.GREEN) if key in active else clr("OFF", C.RED)
            ext_str = clr(", ".join(sorted(exts)[:5]), C.DIM)
            print(f"  [{clr(key, C.YELLOW)}] [{status}]  {clr(label, color):20s}  {ext_str}")
        print(f"\n  [{clr('0', C.WHITE)}] Done / Confirm selection")
        print(f"  [{clr('a', C.WHITE)}] All ON  |  [{clr('n', C.WHITE)}] All OFF")

        choice = input(f"\n  Toggle group number: ").strip().lower()
        if choice == "0" or choice == "":
            break
        elif choice == "a":
            active = set(EXTENSION_GROUPS.keys())
        elif choice == "n":
            active = set()
        elif choice in EXTENSION_GROUPS:
            if choice in active:
                active.remove(choice)
            else:
                active.add(choice)
        print()

    # Build the combined skip_ext set (everything NOT active)
    include_ext = set()
    for key, (_, exts, _) in EXTENSION_GROUPS.items():
        if key in active:
            include_ext |= exts

    # We return the extensions to SKIP (inverse of include)
    all_known = set()
    for _, (_, exts, _) in EXTENSION_GROUPS.items():
        all_known |= exts
    skip_ext = all_known - include_ext

    print(f"\n{ok('Including:')} {clr(', '.join(sorted(include_ext)) or '(none)', C.GREEN)}")
    print(f"{warn('Excluding:')} {clr(', '.join(sorted(skip_ext)) or '(none)', C.DIM)}")
    return skip_ext

# ─── Selective download ────────────────────────────────────────────────────────
def cmd_selective_download():
    """Selective download: pick extensions, then download only missing files."""
    print(bold(clr("\n── SELECTIVE DOWNLOAD ──────────────────────────────────", C.CYAN)))
    skip_ext = pick_extensions()
    records  = parse_manifest(skip_ext=skip_ext)
    if not records:
        return
    missing  = scan_missing(records)
    if not missing:
        print(ok(f"All {len(records)} selected files already downloaded!"))
        return
    print(info(f"Found {len(missing)} missing file(s) to download."))
    _run_download(missing)

# ─── Full (re)download all ─────────────────────────────────────────────────────
def cmd_download_all():
    """Download everything listed in the manifest (skip existing)."""
    print(bold(clr("\n── DOWNLOAD ALL (RESUME SUPPORTED) ─────────────────────", C.CYAN)))
    records = parse_manifest(skip_ext=set())   # no filter
    missing = scan_missing(records)
    if not missing:
        print(ok("Nothing to download — all files present."))
        return
    print(info(f"{len(missing)} file(s) to download."))
    _run_download(missing)

# ─── Download ebooks only (no videos) ─────────────────────────────────────────
def cmd_ebooks_only():
    """Download only ebook-related files (skip all videos)."""
    print(bold(clr("\n── EBOOKS ONLY (NO VIDEOS) ──────────────────────────────", C.CYAN)))
    records = parse_manifest(skip_ext=ALL_VIDEO_EXT)
    missing = scan_missing(records)
    if not missing:
        print(ok("All ebook files already downloaded."))
        return
    print(info(f"{len(missing)} ebook file(s) to download."))
    _run_download(missing)

# ─── Clear state / reset ──────────────────────────────────────────────────────
def cmd_reset_state():
    """Reset the download state file (clears resume cache)."""
    if STATE_FILE.exists():
        STATE_FILE.unlink()
        print(ok("State file cleared. Next download starts fresh."))
    else:
        print(info("No state file found — nothing to clear."))

# ─── Show collection stats ─────────────────────────────────────────────────────
def cmd_stats():
    """Show collection stats: file counts and total size by type."""
    print(bold(clr("\n── COLLECTION STATS ────────────────────────────────────", C.CYAN)))
    if not COLLECTION.exists():
        print(err(f"Collection folder not found: {COLLECTION}"))
        return

    ext_counts = {}
    ext_sizes  = {}
    part_count = 0
    total_size = 0

    for p in COLLECTION.rglob("*"):
        if p.is_file():
            if p.suffix == ".part":
                part_count += 1
                continue
            ext   = p.suffix.lower() or "(no ext)"
            size  = p.stat().st_size
            ext_counts[ext] = ext_counts.get(ext, 0) + 1
            ext_sizes[ext]  = ext_sizes.get(ext, 0) + size
            total_size      += size

    total_files = sum(ext_counts.values())
    print(f"  {'Extension':<15} {'Files':>6}  {'Size':>10}")
    print(f"  {'─'*15}  {'─'*6}  {'─'*10}")
    for ext in sorted(ext_counts, key=lambda e: -ext_sizes.get(e, 0)):
        size_mb = ext_sizes.get(ext, 0) / (1024**2)
        ext_label = clr(f"{ext:<15}", C.CYAN)
        print(f"  {ext_label} {ext_counts[ext]:>6}  {size_mb:>9.1f}M")
    total_gb = total_size / (1024**3)
    print(f"\n  {'TOTAL':<15} {total_files:>6}  {total_gb:>9.2f}G")
    if part_count:
        print(warn(f"\n  {part_count} .part file(s) found — run option 3 to fix."))

# ─── Refresh Manifest (re-scan Drive) ────────────────────────────────────────
def cmd_refresh_manifest():
    """
    Re-scan the Google Drive folder and rebuild gdown_full_list.txt.
    Uses: gdown --folder --remaining-ok <URL> (dry listing via --no-download)
    Since gdown doesn't have a pure list mode, we capture the verbose output
    by running gdown in a temp dir and capturing its stdout.
    """
    print(bold(clr("\n── REFRESH DRIVE MANIFEST ──────────────────────────────", C.CYAN)))
    print(info(f"Drive URL: {DRIVE_URL}"))
    print(info("Scanning Google Drive folder structure… (this may take 1-2 minutes)"))
    print(warn("Do NOT interrupt — let it complete for an accurate manifest.\n"))

    # Backup old manifest
    backup = None
    if MANIFEST.exists():
        backup = BASE / f"gdown_full_list.backup_{datetime.now().strftime('%Y%m%d_%H%M%S')}.txt"
        MANIFEST.rename(backup)
        print(info(f"Old manifest backed up to: {backup.name}"))

    # Run gdown folder scan — capture output to rebuild manifest
    # gdown writes its scan log to stdout when run with --folder
    cmd = [
        sys.executable, "-m", "gdown",
        "--folder", DRIVE_URL,
        "--remaining-ok",
        "--no-download",  # only list, don't actually download
        "-O", str(COLLECTION),
    ]

    # Fallback: gdown may not support --no-download for folder mode
    # So we use the subprocess approach capturing the listing output
    cmd_list = [
        sys.executable, "-c",
        f"""
import sys, gdown
from io import StringIO
import contextlib

output = []
original_print = print
def capture_print(*args, **kwargs):
    output.append(' '.join(str(a) for a in args))
    original_print(*args, **kwargs)

import builtins
builtins.print = capture_print
try:
    gdown.download_folder(
        url='{DRIVE_URL}',
        output='{str(COLLECTION)}',
        quiet=False,
        remaining_ok=True,
        skip_download=True,
    )
except Exception as e:
    original_print(f'Note: {{e}}')
finally:
    builtins.print = original_print

with open('{str(MANIFEST)}', 'w') as f:
    f.write('\\n'.join(output))
original_print('DONE')
"""
    ]

    print(info("Attempting Drive scan via gdown.download_folder …"))
    try:
        result = subprocess.run(
            cmd_list, capture_output=False, text=True, timeout=300
        )
        if MANIFEST.exists() and MANIFEST.stat().st_size > 100:
            lines = sum(1 for _ in open(MANIFEST))
            print(ok(f"Manifest refreshed: {lines} entries written to {MANIFEST.name}"))
            if backup:
                print(info(f"Backup kept at: {backup.name} (delete manually if not needed)"))
        else:
            # Try classic gdown CLI approach as fallback
            print(warn("First attempt incomplete — trying CLI fallback …"))
            _refresh_via_cli(backup)
    except subprocess.TimeoutExpired:
        print(err("Scan timed out after 5 minutes."))
        _restore_backup(backup)
    except Exception as e:
        print(err(f"Scan failed: {e}"))
        _restore_backup(backup)

def _refresh_via_cli(backup):
    """Fallback: run gdown CLI and capture output to file."""
    cmd = [
        "gdown", "--folder", DRIVE_URL,
        "--remaining-ok", "-O", str(COLLECTION)
    ]
    print(info("Running: " + " ".join(cmd)))
    print(warn("This WILL start downloading — press Ctrl+C after the file listing appears."))
    try:
        with open(MANIFEST, "w") as out_f:
            proc = subprocess.Popen(
                cmd, stdout=subprocess.PIPE, stderr=subprocess.STDOUT,
                text=True, bufsize=1
            )
            for line in proc.stdout:
                sys.stdout.write(line)
                out_f.write(line)
            proc.wait()
        lines = sum(1 for _ in open(MANIFEST))
        print(ok(f"Manifest saved: {lines} lines → {MANIFEST.name}"))
    except KeyboardInterrupt:
        print(warn("\nInterrupted — partial manifest saved. Run Verify to check coverage."))
    except FileNotFoundError:
        print(err("gdown CLI not found. Run option [0] to install dependencies."))
        _restore_backup(backup)

def _restore_backup(backup):
    if backup and backup.exists():
        backup.rename(MANIFEST)
        print(warn(f"Restored previous manifest from backup."))

# ─── Install dependencies ──────────────────────────────────────────────────────
def cmd_install():
    """Install gdown and tqdm via pip."""
    print(info("Installing gdown and tqdm…"))
    subprocess.check_call([sys.executable, "-m", "pip", "install", "--quiet", "gdown", "tqdm"])
    print(ok("Done! Please re-run the script."))
    sys.exit(0)

# ══════════════════════════════════════════════════════════════════════════════
# MAIN MENU
# ══════════════════════════════════════════════════════════════════════════════
MENU = [
    ("0",  "Install / Update dependencies (gdown + tqdm)",      cmd_install),
    ("1",  "📊  Verify collection integrity",                   cmd_verify),
    ("2",  "📈  Collection stats (file counts & sizes)",        cmd_stats),
    ("3",  "🔧  Fix broken / .part files & re-download",       cmd_fix),
    ("4",  "⬇️   Download ebooks only  (skip videos)",          cmd_ebooks_only),
    ("5",  "⬇️   Selective download  (pick extensions)",        cmd_selective_download),
    ("6",  "⬇️   Download EVERYTHING (resume supported)",       cmd_download_all),
    ("7",  "🗑️   Reset resume cache (state file)",              cmd_reset_state),
    ("8",  "🔄  Refresh manifest (re-scan Google Drive)",       cmd_refresh_manifest),
    ("q",  "Quit",                                              None),
]

def print_menu():
    print(clr("\n── MAIN MENU ───────────────────────────────────────────", C.CYAN))
    print(clr(f"  Drive : {DRIVE_URL[:60]}…", C.DIM))
    print(clr(f"  Local : {COLLECTION}", C.DIM))
    print()
    for key, label, _ in MENU:
        color = C.RED if key == "q" else C.YELLOW
        print(f"  [{clr(key, color)}]  {label}")
    print()

def main():
    print_header()

    # Quick dependency check
    if not GDOWN_AVAILABLE or not TQDM_AVAILABLE:
        missing_deps = []
        if not GDOWN_AVAILABLE: missing_deps.append("gdown")
        if not TQDM_AVAILABLE:  missing_deps.append("tqdm")
        print(warn(f"Missing packages: {', '.join(missing_deps)}"))
        print(info("Run option [0] to install them automatically.\n"))

    actions = {key: fn for key, _, fn in MENU}

    while True:
        print_menu()
        try:
            choice = input(clr("  Enter choice: ", C.WHITE)).strip().lower()
        except EOFError:
            break

        if choice == "q":
            print(clr("\n  Goodbye!\n", C.CYAN))
            break
        elif choice in actions and actions[choice]:
            try:
                actions[choice]()
            except KeyboardInterrupt:
                print(warn("\nOperation cancelled by user."))
        else:
            print(warn("Invalid choice. Please try again."))

        input(clr("\n  Press ENTER to return to menu…", C.DIM))

if __name__ == "__main__":
    main()
